name: "commala-action"
description: "GitHub Action to run Commala"
author: "Aljoscha Bollmann"
branding:
  icon: check-square
  color: orange
inputs:
  number-of-commits:
    description: "Limit the number of commits to check"
    required: false
    default: ""
runs:
  using: "docker"
  image: "docker://ghcr.io/aljoshare/commala:v0.6.0"
  args:
    - check
    - --config=/github/workspace/.commala.yml
    - HEAD~${{ inputs.number-of-commits }}
