name: "commala-action"
description: "GitHub Action to run Commala"
author: "Aljoscha Bollmann"
branding:
  icon: check-square
  color: orange
inputs:
  report-junit-path:
    description: "Path to write JUnit XML report to"
    required: false
    default: "commala-junit.xml"
  author-name-enabled:
    description: "Whether to check the author name"
    required: false
    default: "true"
  author-email-enabled:
    description: "Whether to check the author email"
    required: false
    default: "true"
  branch-enabled:
    description: "Whether to check the branch name"
    required: false
    default: "true"
  message-enabled:
    description: "Whether to check the commit message"
    required: false
    default: "true"
  signoff-enabled:
    description: "Whether to check for sign-offs"
    required: false
    default: "true"
  first-commit:
    description: "First commit to check"
    required: false
    default: ""
  latest-commit:
    description: "Latest commit to check"
    required: false
    default: ""
runs:
  using: "docker"
  image: "docker://ghcr.io/aljoshare/commala:v0.2.0"
  args:
    - check
    - --report-junit-path
    - ${{ inputs.report-junit-path }}
    - --author-name-enabled
    - ${{ inputs.author-name-enabled }}
    - --author-email-enabled
    - ${{ inputs.author-email-enabled }}
    - --branch-enabled
    - ${{ inputs.branch-enabled }}
    - --message-enabled
    - ${{ inputs.message-enabled }}
    - --signoff-enabled
    - ${{ inputs.signoff-enabled }}
    - ${{ inputs.first-commit }}..${{ inputs.latest-commit }}
